name = "Lorenz63Filter"
uuid = "92ef830e-fee4-4a21-a24f-3affa31ff52a"
authors = ["Grant Bruer gbruer15@gmail.com and contributors"]
version = "0.0.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[compat]
CairoMakie = "0.12.10"
julia = "1.8"
